### ISSUE TITLE
remove double return

### ISSUE THREAD

**Issue by jiahao-0204** [ori-drs/planar_mesh#12]
if a point have a double return point, the double return point will be on the same ray as the first return, thus any triangle formed by the first return will be deleted immediately, making it meaningless.

thus should find ways to remove such duplicated "rays" to speed up

**Comment by jiahao-0204** [comment]
with double return (78097 points / 1.55264 s)
![Screenshot from 2024-11-28 17-37-37](https://github.com/user-attachments/assets/943b6c4b-dfb4-43a6-81bc-c6cbade74c64)
![Screenshot from 2024-11-28 17-42-09](https://github.com/user-attachments/assets/87ddad57-cddc-438e-97c2-8c6429954983)


without double return (41485 points / 1.16695 s)
![Screenshot from 2024-11-28 17-38-24](https://github.com/user-attachments/assets/6d0d92e3-204e-43cc-93f9-7fc237a6b1c1)
![Screenshot from 2024-11-28 17-42-51](https://github.com/user-attachments/assets/dcf31948-d217-4273-ae67-01f664386b08)

**results**
- without double return is faster as there are less points
- surface formed are also larger in size, less silver triangles.

**Comment by mauricefallon** [comment]
So I made your algorithm 25% faster with one comment? .. ;)

**Comment by mauricefallon** [comment]
.... still doing <<any>> computation to clean up this nonsense seems wrong.

Could you implement this as a simple standalone node which we could pass the data through?
> /hesai/pandar --->  duplicate filter node ---> /hesai/pandar_clean

Some of our pipelines use the pandar topic and waste compute multiple times.


```
        // if same azimuth and altitude not already in the map
        if (point_map.find(std::make_pair(azimuth, altitude)) == point_map.end())
        {
            // store azimuth and altitude as key, range and the index of the point as value
            point_map[std::make_pair(azimuth, altitude)] = std::make_pair(range, i);
        }
        else
        {
            // compare range, keep the closer one
            if (range < point_map[std::make_pair(azimuth, altitude)].first)
            {
                point_map[std::make_pair(azimuth, altitude)] = std::make_pair(range, i);
            }
        }

**Comment by jiahao-0204** [comment]
> So I made your algorithm 25% faster with one comment? .. ;)

Hahaha yes, devil's in the details.

**Comment by jiahao-0204** [comment]
> .... still doing <> computation to clean up this nonsense seems wrong.
> 
> Could you implement this as a simple standalone node which we could pass the data through?
> 
> > /hesai/pandar --->  duplicate filter node ---> /hesai/pandar_clean
> 
> Some of our pipelines use the pandar topic and waste compute multiple times.
> 
> ```
>         // if same azimuth and altitude not already in the map
>         if (point_map.find(std::make_pair(azimuth, altitude)) == point_map.end())
>         {
>             // store azimuth and altitude as key, range and the index of the point as value
>             point_map[std::make_pair(azimuth, altitude)] = std::make_pair(range, i);
>         }
>         else
>         {
>             // compare range, keep the closer one
>             if (range < point_map[std::make_pair(azimuth, altitude)].first)
>             {
>                 point_map[std::make_pair(azimuth, altitude)] = std::make_pair(range, i);
>             }
>         }  
> ```

Sure!

**Comment by jiahao-0204** [comment]
> > .... still doing <> computation to clean up this nonsense seems wrong.
> > Could you implement this as a simple standalone node which we could pass the data through?
> > > /hesai/pandar --->  duplicate filter node ---> /hesai/pandar_clean
> > 
> > 
> > Some of our pipelines use the pandar topic and waste compute multiple times.
> > ```
> >         // if same azimuth and altitude not already in the map
> >         if (point_map.find(std::make_pair(azimuth, altitude)) == point_map.end())
> >         {
> >             // store azimuth and altitude as key, range and the index of the point as value
> >             point_map[std::make_pair(azimuth, altitude)] = std::make_pair(range, i);
> >         }
> >         else
> >         {
> >             // compare range, keep the closer one
> >             if (range < point_map[std::make_pair(azimuth, altitude)].first)
> >             {
> >                 point_map[std::make_pair(azimuth, altitude)] = std::make_pair(range, i);
> >             }
> >         }  
> > ```
> 
> Sure!

see [ori-drs/duplicate_filter](https://github.com/ori-drs/duplicate_filter)
